theme: jekyll-theme-slate
title: Welcome to Nana's homepage
description: The homepage of Nana Miyashita,master student in International Media, Communication, and Tourism Studies
plugins:
  - jemoji
url: "https://NanaMiyashita.github.io/"
markdown: kramdown
